[package]
name = "eatbe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "entity", "migration", "entity"]

[dependencies]
rocket = { version = "0.5.0", features = ["secrets", "tls", "json"] }
sea-orm-rocket = "0.5.4"
serde = { version = "1.0", features = ["derive"] }
async-trait = { version = "0.1" } 
sea-orm = { version = "0.12.15", features = ["sqlx-mysql", "runtime-tokio-rustls", "with-uuid"]}
migration = { path = "migration" }
entity = { path = "entity" }
jsonwebtoken = "9.3.0"
chrono = "0.4.38"
calamine = "0.25.0"
rocket_okapi = { version = "0.9.0", features = ["swagger", "rapidoc"] }
schemars = "0.8"
rand = "0.8.5"


[dependencies.uuid]
version = "1.8.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dependencies.sqlx] 
version = "0.7"
default-features = false
features = ["macros", "migrate", "mysql"]

[dependencies.rocket_db_pools]
version = "0.1.0"
features = ["deadpool_redis", "sqlx_mysql"]

